M48
; DRILL file {KiCad 7.0.7} date Tue 31 Oct 2023 10:05:32 AM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-31T10:05:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.6663Y-1.3249
X5.8939Y-1.3249
T2
X3.33Y-6.16
X3.335Y-1.249
X7.355Y-2.025
X7.388Y-6.165
T0
M30
